spring.datasource.hikari.max-lifetime=1000
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=100
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB10Dialect
spring.thymeleaf.cache=true
spring.resources.cache.period=3600

server.error.include-stacktrace=never
spring.jpa.open-in-view=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.error.include-exception=false
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=true

spring.data.web.pageable.max-page-size=2000000000
spring.data.rest.max-page-size=2000000000